// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("NetworkVisualizer")]
[assembly: AssemblyProductAttribute("NetworkVisualizer")]
[assembly: AssemblyDescriptionAttribute("Project has no summmary; update build.fsx")]
[assembly: AssemblyVersionAttribute("0.0.1")]
[assembly: AssemblyFileVersionAttribute("0.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.1";
    }
}
